tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
# Pack, ship and run any application as a lightweight container
brew "docker"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Colorize logfiles and command output
brew "grc"
# Login and retrieve AWS temporary credentials using a SAML IDP
brew "saml2aws"
# Cross-shell prompt for astronauts
brew "starship"
# Voice and text chat software
cask "discord"
# Sans-serif, slab-serif, monospace and quasi‑proportional typeface family
cask "font-iosevka"
# Developer targeted fonts with a high number of glyphs
cask "font-iosevka-nerd-font"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Email client
cask "microsoft-outlook"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Team communication and collaboration software
cask "slack"
