# Cocogitto configuration for .dotfiles.fish
[bump]
# Enable automatic version bumping
auto = true

# Commit types that trigger version bumps
[commit_types]
feat = { bump = "minor", changelog = true }
fix = { bump = "patch", changelog = true }
docs = { bump = "patch", changelog = true }
style = { bump = "patch", changelog = false }
refactor = { bump = "patch", changelog = true }
test = { bump = "patch", changelog = false }
chore = { bump = "patch", changelog = false }
perf = { bump = "patch", changelog = true }
ci = { bump = "patch", changelog = false }
build = { bump = "patch", changelog = false }

# Breaking changes always trigger major bump
[git]
# Use git-emoji format detection
conventional_commits = true

[changelog]
# Path to the changelog file  
path = "CHANGELOG.md"
# Template for changelog generation
template = "default"
# Sections for grouping commits
[changelog.sections]
"New Features" = { types = ["feat"] }
"Bug Fixes" = { types = ["fix"] }
"Performance" = { types = ["perf"] }
"Documentation" = { types = ["docs"] }
"Refactoring" = { types = ["refactor"] }

# Configure git hooks (optional)
[hooks]
# Run tests before bumping version
pre_bump = ["make test"]

# GitHub integration
[github]
# Repository information (auto-detected from git remote)
owner = "srizzling"
repository = ".dotfiles.fish"