

[character]
error_symbol = "[Î»](red)"
success_symbol = "[Î»](purple)"

[aws]
format = ' [$symbol($profile )(\($region\) )(\[$duration\])]($style)'
style = "242"

[aws.region_aliases]
ap-southeast-2 = "ase2"
us-east-1 = "use1"
us-west-2 = "usw2"

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
style = '242'
symbol = 'ó° … '

[hostname]
style = "242"

[cmake]
disabled = true

[cmd_duration]
format = " [$duration]($style)"
min_time = 500

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
read_only = " ðŸ”’"
style = "blue"
truncate_to_repo = true
truncation_length = 0

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = "[$symbol](red)[($branch)]($style)"
style = "242"
symbol = "î‚ "

[git_status]
ahead = "[â‡¡](cyan)"
behind = "[â‡£](cyan)"
diverged = "[â‡¡â‡£](cyan)"
format = '([$modified $ahead_behind]($style))'
modified = "[*](218)"
stashed = "[â‰¡](cyan)"

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true
